/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Admin/Dashboard': RouteRecordInfo<'/Admin/Dashboard', '/Admin/Dashboard', Record<never, never>, Record<never, never>>,
    '/Customer/CustomerHome': RouteRecordInfo<'/Customer/CustomerHome', '/Customer/CustomerHome', Record<never, never>, Record<never, never>>,
    '/Customer/Dashboard': RouteRecordInfo<'/Customer/Dashboard', '/Customer/Dashboard', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/SuperAdmin/Dashboard': RouteRecordInfo<'/SuperAdmin/Dashboard', '/SuperAdmin/Dashboard', Record<never, never>, Record<never, never>>,
    '/SuperAdmin/Home': RouteRecordInfo<'/SuperAdmin/Home', '/SuperAdmin/Home', Record<never, never>, Record<never, never>>,
  }
}
